### ISSUE TITLE
React-Native 0.62 - useNativeDriver

### ISSUE THREAD

**Issue by saimonventura** [ambisign-gavin/react-native-swipe-item#7]
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

**Comment by vtn-dev-sameer** [comment]
same issue

**Comment by josianni** [comment]
Same issue here

**Comment by osamasaeedaltafseer** [comment]
same issue

**Comment by lundjrl** [comment]
Anyone find a workaround for this? I keep getting the warning in my console.

**Comment by vtn-dev-sameer** [comment]
I am still looking for solution.

**Comment by MbIWaTUK** [comment]
same issue

**Comment by biggeb4** [comment]
Hi i hade same issue, fixed by adding, `useNativeDriver: true,` in this line:
`Animated.spring(this.state.panDistance,{toValue:{x:toX,y:0},friction:10})`
like this:
`Animated.spring(this.state.panDistance,{toValue:{x:toX,y:0},friction:10,useNativeDriver: true,})`
in the swipeItem.js file as a workaround until it gets fixed

**Comment by ambisign-gavin** [comment]
https://github.com/ambisign-gavin/react-native-swipe-item/commit/05f767ce9ef9ce799274656c33dca52e963cd226 fixed the problem.
